# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3.0"
services:

  tester:
    image: tester-service
    container_name: mqtt-agent-tester-service
    volumes:
      - ${SOURCE_CODE_VOLUME}\postman:/app
      - ${CACHE_VOLUME}:/cache

  nginx:
    image: mosquitto-agent
    container_name: mqtt-agent-nginx-service
    volumes:
      - ${SOURCE_CODE_VOLUME}\cgi:/usr/share/nginx/html/cgi-bin
      - ${SOURCE_CODE_VOLUME}\html:/usr/share/nginx/html
    ports:
      - 8080:80

  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mqtt-agent-mosquitto-service
    ports:
      - 1883:1883
      - 9001:9001

networks:
  default:
    driver: bridge
    name: mqtt-test-network
